FROM node:22.12.0-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/

RUN npm install -g pnpm && pnpm install

COPY . .

WORKDIR /app/apps/backend

RUN pnpm run build

EXPOSE 4000

CMD ["pnpm", "start"]
